/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#b7c8e1",
        "surface-container-high": "#222a3d",
        "surface-container-low": "#131b2e",
        "tertiary-fixed": "#ffdbc8",
        "outline": "#8f8fa0",
        "outline-variant": "#454655",
        "secondary": "#b7c8e1",
        "on-background": "#dae2fd",
        "on-error-container": "#ffdad6",
        "surface-dim": "#0b1326",
        "on-primary-fixed-variant": "#222fc2",
        "primary-fixed": "#e0e0ff",
        "on-tertiary-fixed-variant": "#743500",
        "surface-container-highest": "#2d3449",
        "surface-container-lowest": "#060e20",
        "on-primary-fixed": "#000569",
        "on-error": "#690005",
        "tertiary-fixed-dim": "#ffb689",
        "on-tertiary-container": "#fffdff",
        "on-secondary-fixed-variant": "#38485d",
        "on-secondary-container": "#a9bad3",
        "tertiary-container": "#bb5a00",
        "secondary-container": "#3a4a5f",
        "on-surface": "#dae2fd",
        "tertiary": "#ffb689",
        "inverse-primary": "#3f4cda",
        "on-primary": "#000da4",
        "on-primary-container": "#fffdff",
        "surface": "#0b1326",
        "surface-variant": "#2d3449",
        "background": "#0b1326",
        "on-surface-variant": "#c6c5d7",
        "on-tertiary-fixed": "#311300",
        "error-container": "#93000a",
        "surface-bright": "#31394d",
        "primary-fixed-dim": "#bec2ff",
        "inverse-on-surface": "#283044",
        "surface-container": "#171f33",
        "primary": "#bec2ff",
        "on-tertiary": "#512300",
        "surface-tint": "#bec2ff",
        "on-secondary": "#213145",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#0b1c30",
        "secondary-fixed": "#d3e4fe",
        "primary-container": "#5865f2",
        "inverse-surface": "#dae2fd"
      },
      fontFamily: {
        "geist": ["Geist", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}
